[workspace]
authors = ["Yanwei Ye <cydia2001@duck.com>"]
channels = ["conda-forge"]
name = "ComfyUI-Workflows-ZHO"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
requests = ">=2.32.4,<3"

[pypi-dependencies]
diffusers = ">=0.34.0, <0.35"
torch = ">=2.7.1, <3"
transformers = ">=4.53.1, <5"
